
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from corsheaders.defaults import default_headers
from pathlib import Path # import libraries for file path handling 1
from datetime import timedelta
from dotenv import load_dotenv
import pymysql

# Load environment variables from .env file
load_dotenv()

# Initialize PyMySQL as MySQL client
pymysql.install_as_MySQLdb()

import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-9kwe&kr)&kk3lj=+(d6^0!5+9*fzhq=r7gg4yy+_oiilr3^e#(')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',') if os.getenv('ALLOWED_HOSTS') else [
    "api.lunarismanagement.com",
    "lunarismanagement.com",
    "www.lunarismanagement.com",
    "localhost",
    "127.0.0.1",
]


REST_FRAMEWORK = { 
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}
SIMPLE_JWT = {                                     # specific settings for JWT  3
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework for building APIs   4
    "api",
    "corsheaders",  # CORS headers for cross-origin requests
    "social_django",
    "adminpanel",  # Your custom admin panel apps
    "author_management",  # Your custom author management app
]

MIDDLEWARE = [
      'corsheaders.middleware.CorsMiddleware',  # Middleware for handling CORS 5
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
  
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'hilal_backend',             # your database name
#         'USER': 'root',             # your MySQL username
#         'PASSWORD':'Mysql123+++', # your MySQL password
#         'HOST': 'localhost',        # or 127.0.0.1
#         'PORT': '3307',
#     }dd
# } 


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'hilal_backend',             # your database name
#         'USER': 'root',             # your MySQL username
#         'PASSWORD':'Mysql123+++', # your MySQL password
#         'HOST': 'localhost',        # or 127.0.0.1
#         'PORT': '3307',
#     }
# }



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DATABASE_NAME', 'hilal_database'),
        'USER': os.getenv('DATABASE_USER', 'root'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
        'HOST': os.getenv('DATABASE_HOST', 'localhost'),
        'PORT': os.getenv('DATABASE_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# Override Django's MariaDB version check to work with 10.4.32
import django.db.backends.mysql.base as mysql_base
import django.db.backends.mysql.features as mysql_features

# Monkey patch to bypass MariaDB version check and disable RETURNING clause
def patched_minimum_database_version(self):
    if self.connection.mysql_is_mariadb:
        return (10, 4)  # Allow MariaDB 10.4
    else:
        return (5, 7)   # MySQL 5.7

# Disable RETURNING clause support for MariaDB 10.4
def patched_can_return_columns_from_insert(self):
    return False

mysql_features.DatabaseFeatures.minimum_database_version = property(patched_minimum_database_version)
mysql_features.DatabaseFeatures.can_return_columns_from_insert = property(patched_can_return_columns_from_insert)



# DATABASES = {


#     'default': {

#         'ENGINE': 'django.db.backends.mysql',


#         'NAME': 'hilal_database',             # your database name


#         'USER': 'admin',             # your MySQL username


#         'PASSWORD':'database_password', # your MySQL password


#         'HOST': 'database-2.cszw0uku8hw1.us-east-1.rds.amazonaws.com',        # or 127.0.0.1

#         'PORT': '3306',

#     }

# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS_ALLOWED_ORIGINS = [
#     "https://hilalclient.vercel.app",  # Allow frontend development server
# ]
# CORS_ALLOWED_ORIGINS = [ # Allow frontend development server
#     "https://hilalclient.vercel.app",  # Allow production frontend
# ]

CORS_ALLOWED_ORIGINS = [
    "https://lunarismanagement.com",
    "https://www.lunarismanagement.com",
    "http://localhost:5173",  # Allow frontend development server
]
# CORS_ALLOWED_CREDENTIALS = True  # Allow credentials for CORS; adjust in production

# Allow cookies to be sent
CORS_ALLOW_CREDENTIALS = True

# Allow all headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'X-Requested-With',
]

# CSRF_TRUSTED_ORIGINS = [
#     "https://hilalclient.vercel.app",
# ]

CSRF_TRUSTED_ORIGINS = [
    "https://lunarismanagement.com",
    "https://www.lunarismanagement.com",
    "http://localhost:5173",
]
# Optional: allow specific methods
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS"
]

AUTH_USER_MODEL = "api.CustomUser"

#helloi

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Replace with your actual Facebook app credentials
SOCIAL_AUTH_FACEBOOK_KEY = '24151840021077228'
SOCIAL_AUTH_FACEBOOK_SECRET = '3c579a7a679998c267f5fc1affc2ece9'

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email, first_name, last_name'
}

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


