# Generated by Django 5.2.4 on 2025-07-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': True},
        ),
    ]
