# Generated by Django 5.2.4 on 2025-07-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_articles_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False},
        ),
    ]
