# Generated by Django 5.2.4 on 2025-08-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_articles_options_alter_comments_options_and_more'), 
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publish_date', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('LTR', 'Left-to-Right'), ('RTL', 'Right-to-Left')], max_length=3)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
                ('cover_image', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ebooks',
                'managed': False,
            },
        ),
    ]
