# Generated by Django 5.2.4 on 2025-08-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_ebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ebook',
        ),
    ]
