# Generated by Django 5.2.4 on 2025-08-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_authors'),
        ('adminpanel', '0006_delete_ebook'),
    ]

    operations = [
    ]
