# Generated by Django 5.2.4 on 2025-08-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_ebook_alter_authors_options_alter_videos_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authors',
            table='authors',
        ),
    ]
