# Generated by Django 5.2.4 on 2025-08-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_authors_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authors',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='billboards',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ebook',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='magazines',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'managed': True, 'ordering': ['order', 'created_at']},
        ),
    ]
