# Generated by Django 5.2.4 on 2025-08-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_articles_section_articles_user_billboards_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authors',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='billboards',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ebook',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='magazines',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'managed': False, 'ordering': ['order', 'created_at']},
        ),
    ]
