# Generated by Django 5.2.4 on 2025-09-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_add_video_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'managed': True, 'ordering': ['order', 'created_at']},
        ),
    ]
