# Generated by Django 5.2.4 on 2025-09-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_alter_videos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='language',
            field=models.CharField(
                choices=[('English', 'English'), ('Urdu', 'Urdu')],
                default='English',
                max_length=10
            ),
        ),
    ]
