# Generated by Django 4.2.14 on 2025-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_auto_20250902_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='time_ago',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='views',
        ),
        migrations.AlterField(
            model_name='videos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
