# Generated by Django 4.2.14 on 2025-10-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_publications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='language',
        ),
    ]
