# Generated by Django 4.2.14 on 2025-10-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_remove_publications_description_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE articles ADD COLUMN publication_id BIGINT NULL;",
            reverse_sql="ALTER TABLE articles DROP COLUMN publication_id;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE articles ADD CONSTRAINT articles_publication_id_fk FOREIGN KEY (publication_id) REFERENCES publications(id);",
            reverse_sql="ALTER TABLE articles DROP FOREIGN KEY articles_publication_id_fk;"
        ),
    ]
