# Generated by Django 4.2.14 on 2025-10-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_auto_20251007_1227'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE articles ADD COLUMN magazine_id INT NULL;",
            reverse_sql="ALTER TABLE articles DROP COLUMN magazine_id;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE articles ADD CONSTRAINT articles_magazine_id_fk FOREIGN KEY (magazine_id) REFERENCES magazines(id);",
            reverse_sql="ALTER TABLE articles DROP FOREIGN KEY articles_magazine_id_fk;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE magazines ADD COLUMN publication_id BIGINT NULL;",
            reverse_sql="ALTER TABLE magazines DROP COLUMN publication_id;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE magazines ADD CONSTRAINT magazines_publication_id_fk FOREIGN KEY (publication_id) REFERENCES publications(id);",
            reverse_sql="ALTER TABLE magazines DROP FOREIGN KEY magazines_publication_id_fk;"
        ),
    ]
