# Generated by Django 4.2.14 on 2025-10-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_categories'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE articles ADD COLUMN category_id BIGINT NULL;",
            reverse_sql="ALTER TABLE articles DROP COLUMN category_id;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE articles ADD CONSTRAINT articles_category_id_fk FOREIGN KEY (category_id) REFERENCES categories(id);",
            reverse_sql="ALTER TABLE articles DROP FOREIGN KEY articles_category_id_fk;"
        ),
    ]
