# Generated by Django 4.2.14 on 2025-10-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_auto_20251008_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.publications'),
        ),
    ]
