# Generated by Django 4.2.14 on 2025-10-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_categories_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='path',
        ),
    ]
