# Generated by Django 4.2.14 on 2025-10-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_remove_categories_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='display_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
