# Generated by Django 4.2.14 on 2025-10-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_publications_display_name'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE articles DROP COLUMN category;",
            reverse_sql="ALTER TABLE articles ADD COLUMN category VARCHAR(100);"
        ),
    ]
