# Generated by Django 4.2.14 on 2025-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_add_magazine_year_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the publication', null=True),
        ),
    ]
