# Generated by Django 4.2.14 on 2025-10-15 11:20

from django.db import migrations


def fix_articles_author_id_type(apps, schema_editor):
    """
    Fix the data type mismatch between articles.author_id and authors.id:
    1. Drop the existing foreign key constraint
    2. Modify author_id column from int to bigint unsigned
    3. Recreate the foreign key constraint
    """
    with schema_editor.connection.cursor() as cursor:
        # Drop the existing foreign key constraint
        cursor.execute("ALTER TABLE articles DROP FOREIGN KEY articles_author_id_fk")
        
        # Modify the author_id column to match authors.id (bigint unsigned)
        cursor.execute("ALTER TABLE articles MODIFY COLUMN author_id bigint unsigned DEFAULT NULL")
        
        # Recreate the foreign key constraint
        cursor.execute("ALTER TABLE articles ADD CONSTRAINT articles_author_id_fk FOREIGN KEY (author_id) REFERENCES authors (id)")


def reverse_fix_articles_author_id_type(apps, schema_editor):
    """
    Reverse the data type fix
    """
    with schema_editor.connection.cursor() as cursor:
        # Drop the foreign key constraint
        cursor.execute("ALTER TABLE articles DROP FOREIGN KEY articles_author_id_fk")
        
        # Revert author_id column back to int
        cursor.execute("ALTER TABLE articles MODIFY COLUMN author_id int DEFAULT NULL")
        
        # Recreate the foreign key constraint
        cursor.execute("ALTER TABLE articles ADD CONSTRAINT articles_author_id_fk FOREIGN KEY (author_id) REFERENCES authors (id)")


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0032_cleanup_articles_schema'),
    ]

    operations = [
        migrations.RunPython(
            fix_articles_author_id_type,
            reverse_fix_articles_author_id_type,
        ),
    ]
