# Generated by Django 4.2.14 on 2025-10-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0033_fix_articles_author_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
