# Generated by Django 4.2.14 on 2025-10-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0034_publications_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': True},
        ),
    ]
