# Generated by Django 4.2.14 on 2025-10-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0035_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='publish_date_month',
            field=models.IntegerField(blank=True, help_text='Month extracted from publish_date (1-12)', null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='publish_date_year',
            field=models.IntegerField(blank=True, help_text='Year extracted from publish_date', null=True),
        ),
    ]
