# Generated by Django 4.2.14 on 2025-10-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0037_add_contributors_model'),
        ('adminpanel', '0038_add_contributors_model'),
    ]

    operations = [
    ]
