# Generated by Django 4.2.14 on 2025-10-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0039_merge_20251022_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributors',
            options={'managed': True, 'ordering': ['publication', 'order', 'name']},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='user',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='writer',
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.authors'),
        ),
        migrations.AddField(
            model_name='articles',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.magazines'),
        ),
        migrations.AddField(
            model_name='articles',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.publications'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.categories'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
