# Generated by Django 4.2.14 on 2025-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0040_alter_contributors_options_remove_articles_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='urdu_name',
            field=models.CharField(blank=True, help_text='Display name in Urdu', max_length=255, null=True),
        ),
    ]
