# Generated by Django 4.2.14 on 2025-10-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0041_add_urdu_name_to_publications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='urdu_name',
        ),
    ]
